# Site settings
title: pemtpemt14
description: 'pemtpemt14`s Personal Blog'
url: 'https://pemtpemt14.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'pemtpemt14'
  email: pemtpemt14@gmail.com
  # twitter_username: pemtpemt14
  # facebook_username: pemtpemt14
  # github_username:  pemtpemt14
  # linkedin_username:  pemtpemt14

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
